---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: orange
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/elxreno/zsync/repo/fedora-%OS_VERSION%/elxreno-zsync-fedora-%OS_VERSION%.repo
      
    install: # See base packages https://github.com/ublue-os/main/blob/main/packages.json
      - micro
      - starship
      - gcc
      - gparted
      - mc
      - pluma
      - python3-pip
      - procps-ng
      - rsync
      - samba
      - samba-client
      - syncthing
      - tailscale
      - zsync
      - yt-dlp
   
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.Evince
        # org.gnome.Extensions
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Maps
        - org.gnome.NautilusPreviewer
        - org.gnome.Snapshot
        - org.gnome.TextEditor
        - org.gnome.Weather
        - org.gnome.baobab
        - org.gnome.clocks
        - org.gnome.font-viewer
        
        - org.gnome.Evolution
        - org.gnome.gedit
        - org.gnome.Gnote
        - org.gnome.gedit
        - org.gnome.Gnote
        - org.gnome.gThumb
        - org.gnome.Papers
        - org.gnome.Rhythmbox3
        - org.gnome.SimpleScan
        - org.gnome.Snapshot
        
        - org.freac.freac 
        - org.gimp.GIMP
        - org.kde.kid3
        - org.kde.kdenlive
        - org.keepassxc.KeePassXC
        - org.mozilla.firefox
        - org.signal.Signal
        - org.telegram.desktop
        - org.videolan.VLC

        - com.github.tchx84.Flatseal
        - com.github.rafostar.Clapper
        - com.google.Chrome
        - com.mattjakeman.ExtensionManager
        - com.spotify.Client
        - com.vixalien.sticky
        - io.bassi.Amberol
        - it.mijorus.gearlever
  
  - type: systemd
    system: 
      enabled:
        - smb.service
        - nfs-server.service
        - rpcbind.service
        - sshd.service
        
    user:
      enabled:
        - syncthing.service
        
    user: {} # Also add Flathub user repo, but no user packages
    
  - type: bling
    install:
        - negativo17
  
  - type: gnome-extensions
    install:
        - 615 # AppIndicator and KStatusNotifierItem Support https://extensions.gnome.org/extension/615/appindicator-support/
        - 307 # Dash-to-dock https://extensions.gnome.org/extension/307/dash-to-dock/
        - 2 # Frippery Move Clock https://extensions.gnome.org/extension/2/move-clock/
        - 1319 # GSConnect https://extensions.gnome.org/extension/1319/gsconnect/
        - 6655 # OpenWeather Refined https://extensions.gnome.org/extension/6655/openweather/
        - 4 # Frippery Panel Favorites https://extensions.gnome.org/extension/4/panel-favorites/
        - 6139 # Tailscale QS https://extensions.gnome.org/extension/6139/tailscale-qs/
        - 1460 # Vitals https://extensions.gnome.org/extension/1460/vitals/
        - 602 # Window List by fmuellner https://extensions.gnome.org/extension/602/window-list/
  
  - type: fonts
    fonts:
      google-fonts:
       - Lato
       - Merriweather
       - Montserrat
       - Oswald
       - Open Sans
       - PT Sans
       - Raleway
       - Roboto
       - Slabo
       - Source Sans 3

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
