---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: orange
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
      - https://copr.fedorainfracloud.org/coprs/elxreno/zsync/repo/fedora-%OS_VERSION%/elxreno-zsync-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/useidel/signal-desktop/repo/fedora-41/useidel-signal-desktop-fedora-41.repo
      
    install: # See base packages https://github.com/ublue-os/main/blob/main/packages.json
      # micro
      # starship
      - gcc
      - gparted
      # libreoffice
      # mc
      - pluma
      # python3-pip
      # procps-ng
      - signal-desktop
      - samba
      - samba-client
      - syncthing
      - tailscale
      - vlc
      - vlc-plugin-gnome
      - yt-dlp
      - zsync
   
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
        # silverblue default apps
        - org.gnome.Calculator # Calculator
        - org.gnome.Calendar # Calendar
        - org.gnome.Characters # Characters
        - org.gnome.Connections # Connections
        - org.gnome.Contacts # Contacts
        - org.gnome.Evince # Document Viewer
        # org.gnome.Extensions # Manage GNOME Extensions
        - org.gnome.Logs # Logs
        - org.gnome.Loupe # Image Viewer
        - org.gnome.Maps # Maps
        - org.gnome.NautilusPreviewer
        - org.gnome.Snapshot # Camera
        - org.gnome.TextEditor # Text Editor
        - org.gnome.Weather
        - org.gnome.baobab # Disk Usage Analyzer
        - org.gnome.clocks
        - org.gnome.font-viewer

        # additional apps
        # org.gnome.Boxes # Boxes
        - org.gnome.Evolution # Evolution
        # org.gnome.gedit # Gedit
        - org.gnome.Gnote # Gnote
        - org.gnome.gThumb # gThumb Image Viewer
        - org.gnome.Papers # Papers
        - org.gnome.Rhythmbox3 # Rhythmbox
        - org.gnome.SimpleScan # Document Scanner
        
        - org.freac.freac # fre:ac Audio converter and CD ripper
        - org.gimp.GIMP # GNU Image Create images and edit photographs
        - org.kde.kid3 # Kid3
        - org.kde.kdenlive # Kdenlive
        - org.keepassxc.KeePassXC # KeePassXC
        # org.libreoffice.LibreOffice # The LibreOffice productivity suite
        - org.mozilla.firefox # Firefox Web Browser
        # org.signal.Signal # Signal Desktop
        - org.telegram.desktop # Telegram Desktop
        # org.videolan.VLC # VLC Player

        - com.github.tchx84.Flatseal # Flatseal
        - com.github.rafostar.Clapper # Clapper
        - com.google.Chrome # Google CHrome
        - com.mattjakeman.ExtensionManager # Extension Manager
        - com.spotify.Client # Spotify Desktop
        - com.vixalien.sticky # Sticky Notes
        - io.bassi.Amberol # Amberol Music Player
        - io.github.flattool.Warehouse # App Manager for Flatpak
        - io.github.ungoogled_software.ungoogled_chromium # Ungoogled Chromium
        - it.mijorus.gearlever # Gear Lever Manage AppImages
  
  - type: systemd
    system: 
      enabled:
        - smb.service
        - nfs-server.service
        - rpcbind.service
        - sshd.service
        
    user:
      enabled:
        - syncthing.service
        
    user: {} # Also add Flathub user repo, but no user packages
    
  - type: bling
    install:
        - negativo17
  
  - type: gnome-extensions
    install:
        - 615 # AppIndicator and KStatusNotifierItem Support https://extensions.gnome.org/extension/615/appindicator-support/
        - 307 # Dash-to-dock https://extensions.gnome.org/extension/307/dash-to-dock/
        - 2 # Frippery Move Clock https://extensions.gnome.org/extension/2/move-clock/
        - 1319 # GSConnect https://extensions.gnome.org/extension/1319/gsconnect/
        - 6655 # OpenWeather Refined https://extensions.gnome.org/extension/6655/openweather/
        - 4 # Frippery Panel Favorites https://extensions.gnome.org/extension/4/panel-favorites/
        - 6139 # Tailscale QS https://extensions.gnome.org/extension/6139/tailscale-qs/
        - 1460 # Vitals https://extensions.gnome.org/extension/1460/vitals/
        - 602 # Window List by fmuellner https://extensions.gnome.org/extension/602/window-list/
  
  - type: fonts
    fonts:
      google-fonts:
       - Lato
       - Merriweather
       - Montserrat
       - Oswald
       - Open Sans
       - PT Sans
       - Raleway
       - Roboto
       - Slabo
       - Source Sans 3

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
